"use client";

import { useState, useRef, useEffect } from "react";

const QUICK_ACTIONS = [
  { label: "NTPC Notes banao", text: "Mujhe RRB NTPC ke notes chahiye" },
  { label: "SSC CGL Flashcards", text: "SSC CGL ke flashcards generate karo" },
  { label: "YouTube se notes", text: "YouTube video se notes kaise banau?" },
  { label: "Features batao", text: "Is app mein kya kya features hain?" },
  { label: "Best subject?", text: "Kaunsa subject pehle padhu NTPC ke liye?" },
  { label: "Preparation tips", text: "Exam preparation ke tips do" },
];

const WELCOME_MESSAGE = {
  role: "assistant",
  content: `Namaste! Main hoon NotesAI Helper 🤖

Main tumhari exam preparation mein madad karunga. Yeh app kya-kya kar sakta hai:

📚 **Notes** - Kisi bhi exam ka subject-wise detailed notes
🃏 **Flashcards** - Interactive question-answer cards
🎬 **YouTube Notes** - Video link se automatic notes
📥 **Download** - HTML file mein download karo

Batao kya banana chahte ho? Ya koi sawaal hai?`,
};

export default function ChatBot({ apiKey, onAction }) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([WELCOME_MESSAGE]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [loadingStatus, setLoadingStatus] = useState("");
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 300);
    }
  }, [isOpen]);

  const downloadNotesHtml = (html, meta) => {
    const title = meta
      ? `${meta.exam} - ${meta.subject}${meta.topic ? " - " + meta.topic : ""} Notes`
      : "AI Generated Notes";

    const fullHtml = `<!DOCTYPE html>
<html lang="hi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Notes — ${title}</title>
<style>
  body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;padding:20px 30px;background:#fff;color:#333;line-height:1.8}
  h1{color:#1e1b4b;border-bottom:3px solid #6366f1;padding-bottom:8px;font-size:1.5em;margin-top:20px}
  h2{color:#312e81;border-bottom:2px solid #e0e7ff;padding-bottom:6px;font-size:1.25em;margin-top:25px}
  h3{color:#3730a3;font-size:1.1em;margin-top:20px}
  ul,ol{padding-left:20px} li{margin:4px 0}
  table{border-collapse:collapse;width:100%;margin:15px 0}
  th,td{border:1px solid #e2e8f0;padding:8px 12px;text-align:left}
  th{background:#eef2ff;font-weight:600;color:#312e81}
  tr:nth-child(even){background:#f8fafc}
  blockquote{border-left:4px solid #6366f1;padding:10px 15px;background:#eef2ff;margin:15px 0;border-radius:0 8px 8px 0}
  strong{color:#312e81}
  mark{background:#fef08a;padding:2px 6px;border-radius:4px}
  p{margin:8px 0;line-height:1.8}
  @media print{body{padding:10px}}
</style></head><body>
${html}
<footer style="margin-top:40px;padding-top:15px;border-top:2px solid #e0e7ff;color:#94a3b8;font-size:0.85em;text-align:center">
  Generated by AI Notes Maker | ${new Date().toLocaleDateString("hi-IN")}
</footer>
</body></html>`;

    const blob = new Blob([fullHtml], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9\u0900-\u097F\s-]/g, "_")}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const sendMessage = async (text) => {
    const userMsg = text || input.trim();
    if (!userMsg || loading) return;

    const newMessages = [...messages, { role: "user", content: userMsg }];
    setMessages(newMessages);
    setInput("");
    setLoading(true);
    setLoadingStatus("Soch raha hoon...");

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: newMessages.map((m) => ({
            role: m.role,
            content: m.content,
          })),
          apiKey: apiKey || undefined,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Chat failed");
      }

      const msgObj = {
        role: "assistant",
        content: data.message,
      };

      if (data.generatedHtml) {
        msgObj.generatedHtml = data.generatedHtml;
        msgObj.notesMeta = data.notesMeta;
      }

      if (data.action) {
        msgObj.action = data.action;
      }

      setMessages((prev) => [...prev, msgObj]);
    } catch (err) {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: `Sorry, error aa gaya: ${err.message}. Dubara try karo!`,
        },
      ]);
    } finally {
      setLoading(false);
      setLoadingStatus("");
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  const handleAction = (action) => {
    if (onAction && action) {
      onAction(action);
      setIsOpen(false);
    }
  };

  return (
    <>
      {/* Chat Toggle Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="chat-toggle"
        aria-label="Open AI Helper"
      >
        {isOpen ? (
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        ) : (
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
          </svg>
        )}
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div className="chat-window slide-up">
          {/* Header */}
          <div className="chat-header">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-sm font-bold">
                AI
              </div>
              <div>
                <p className="text-white font-semibold text-sm">NotesAI Helper</p>
                <p className="text-emerald-400 text-xs flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 inline-block" />
                  Online
                </p>
              </div>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="text-slate-400 hover:text-white transition-colors p-1"
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>

          {/* Messages */}
          <div className="chat-messages">
            {messages.map((msg, i) => (
              <div key={i} className={`chat-msg ${msg.role === "user" ? "chat-msg-user" : "chat-msg-bot"}`}>
                <div
                  className={`chat-bubble ${msg.role === "user" ? "chat-bubble-user" : "chat-bubble-bot"}`}
                  dangerouslySetInnerHTML={{
                    __html: msg.content
                      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                      .replace(/\n/g, "<br/>"),
                  }}
                />

                {/* Generated Notes Inline */}
                {msg.generatedHtml && (
                  <div className="chat-notes-container">
                    <div className="chat-notes-header">
                      <span>&#128218; Generated Notes</span>
                      <button
                        onClick={() => downloadNotesHtml(msg.generatedHtml, msg.notesMeta)}
                        className="chat-notes-download"
                      >
                        &#11015; Download HTML
                      </button>
                    </div>
                    <div
                      className="chat-notes-content"
                      dangerouslySetInnerHTML={{ __html: msg.generatedHtml }}
                    />
                  </div>
                )}

                {msg.action && (
                  <button
                    onClick={() => handleAction(msg.action)}
                    className="chat-action-btn"
                  >
                    &#9889; {msg.action.type === "notes"
                      ? "Notes Generate Karo"
                      : msg.action.type === "flashcards"
                        ? "Flashcards Generate Karo"
                        : "YouTube Notes Banao"}
                  </button>
                )}
              </div>
            ))}

            {loading && (
              <div className="chat-msg chat-msg-bot">
                <div className="chat-bubble chat-bubble-bot">
                  <div className="chat-typing">
                    <span /><span /><span />
                  </div>
                  {loadingStatus && (
                    <p className="text-xs text-slate-400 mt-1">{loadingStatus}</p>
                  )}
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          {/* Quick Actions */}
          {messages.length <= 1 && (
            <div className="chat-quick-actions">
              {QUICK_ACTIONS.map((qa, i) => (
                <button
                  key={i}
                  onClick={() => sendMessage(qa.text)}
                  className="chat-quick-btn"
                >
                  {qa.label}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          <div className="chat-input-area">
            <input
              ref={inputRef}
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Kuch bhi poocho..."
              className="chat-input"
              disabled={loading}
            />
            <button
              onClick={() => sendMessage()}
              disabled={loading || !input.trim()}
              className="chat-send-btn"
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="22" y1="2" x2="11" y2="13" />
                <polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
            </button>
          </div>
        </div>
      )}
    </>
  );
}
